var target = document.querySelector('ol');

// создаём экземпляр MutationObserver
var observer = new MutationObserver(function (allmutations) {

    allmutations.map((mr) => {
        console.log('Тип изменения: ' + mr.type + 'Измененный элемент: ' + mr.target);
    });

});

// конфигурация нашего observer:
var config = { childList: true, characterData: true, subtree: true };

// передаём в качестве аргументов целевой элемент и его конфигурацию
observer.observe(target, config);



[object MutationRecord] {
    addedNodes: [object NodeList] {
        0: [object HTMLLIElement] { ... },
        entries: function entries() { [native code] },
        forEach: function forEach() { [native code] },
        item: function item() { [native code] },
        keys: function keys() { [native code] },
        length: 1,
            values: function values() { [native code] }
    },
    attributeName: null,
        attributeNamespace: null,
            nextSibling: [object Text] {
        addEventListener: function addEventListener() { [native code] },
        after: function after() { [native code] },
        appendChild: function appendChild() { [native code] },
        appendData: function appendData() { [native code] },
        assignedSlot: null,
            ATTRIBUTE_NODE: 2,
                baseURI: "https://null.jsbin.com/runner",
                    before: function before() { [native code] },
        CDATA_SECTION_NODE: 4,
            childNodes: [object NodeList] { ... },
        cloneNode: function cloneNode() { [native code] },
        COMMENT_NODE: 8,
            compareDocumentPosition: function compareDocumentPosition() { [native code] },
        contains: function contains() { [native code] },
        data: "
        ",
        deleteData: function deleteData() { [native code] },
        dispatchEvent: function dispatchEvent() { [native code] },
        DOCUMENT_FRAGMENT_NODE: 11,
            DOCUMENT_NODE: 9,
                DOCUMENT_POSITION_CONTAINED_BY: 16,
                    DOCUMENT_POSITION_CONTAINS: 8,
                        DOCUMENT_POSITION_DISCONNECTED: 1,
                            DOCUMENT_POSITION_FOLLOWING: 4,
                                DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
                                    DOCUMENT_POSITION_PRECEDING: 2,
                                        DOCUMENT_TYPE_NODE: 10,
                                            ELEMENT_NODE: 1,
                                                ENTITY_NODE: 6,
                                                    ENTITY_REFERENCE_NODE: 5,
                                                        firstChild: null,
                                                            getDestinationInsertionPoints: function getDestinationInsertionPoints() { [native code] },
        getRootNode: function getRootNode() { [native code] },
        hasChildNodes: function hasChildNodes() { [native code] },
        insertBefore: function insertBefore() { [native code] },
        insertData: function insertData() { [native code] },
        isConnected: true,
            isDefaultNamespace: function isDefaultNamespace() { [native code] },
        isEqualNode: function isEqualNode() { [native code] },
        isSameNode: function isSameNode() { [native code] },
        lastChild: null,
            length: 1,
                lookupNamespaceURI: function lookupNamespaceURI() { [native code] },
        lookupPrefix: function lookupPrefix() { [native code] },
        nextElementSibling: null,
            nextSibling: null,
                nodeName: "#text",
                    nodeType: 3,
                        nodeValue: "
        ",
        normalize: function normalize() { [native code] },
        NOTATION_NODE: 12,
            ownerDocument: [object HTMLDocument] { ... },
        parentElement: [object HTMLOListElement] { ... },
        parentNode: [circular object HTMLOListElement] :
        <ol contenteditable="" oninput="">
            <li>Press enter</li><li><br></li>
      </ol>,
            previousElementSibling: [circular object HTMLLIElement] :
  <li><br></li>,
                previousSibling: [circular object HTMLLIElement] :
  <li><br></li>,
                    PROCESSING_INSTRUCTION_NODE: 7,
      remove: function remove() {[native code]},
      removeChild: function removeChild() {[native code]},
      removeEventListener: function removeEventListener() {[native code]},
      replaceChild: function replaceChild() {[native code]},
      replaceData: function replaceData() {[native code]},
      replaceWith: function replaceWith() {[native code]},
      splitText: function splitText() {[native code]},
      substringData: function substringData() {[native code]},
                    TEXT_NODE: 3,
                    textContent: "
                ",
                    wholeText: "
                "
                  },
                  oldValue: null,
    previousSibling: [object HTMLLIElement] {
                        accessKey: "",
      addEventListener: function addEventListener() {[native code]},
      after: function after() {[native code]},
      animate: function animate() {[native code]},
      append: function append() {[native code]},
      appendChild: function appendChild() {[native code]},
                    assignedSlot: null,
      attachShadow: function attachShadow() {[native code]},
                    ATTRIBUTE_NODE: 2,
      attributes: [object NamedNodeMap] {... },
      attributeStyleMap: [object StylePropertyMap] {... },
                    autocapitalize: "",
                    baseURI: "https://null.jsbin.com/runner",
      before: function before() {[native code]},
      blur: function blur() {[native code]},
                    CDATA_SECTION_NODE: 4,
                    childElementCount: 0,
      childNodes: [object NodeList] {... },
      children: [object HTMLCollection] {... },
      classList: [object DOMTokenList] {... },
                    className: "",
      click: function click() {[native code]},
                    clientHeight: 18,
                    clientLeft: 0,
                    clientTop: 0,
                    clientWidth: 385,
      cloneNode: function cloneNode() {[native code]},
      closest: function closest() {[native code]},
                    COMMENT_NODE: 8,
      compareDocumentPosition: function compareDocumentPosition() {[native code]},
      computedStyleMap: function computedStyleMap() {[native code]},
      contains: function contains() {[native code]},
                    contentEditable: "inherit",
      createShadowRoot: function createShadowRoot() {[native code]},
      dataset: [object DOMStringMap] {... },
                    dir: "",
      dispatchEvent: function dispatchEvent() {[native code]},
                    DOCUMENT_FRAGMENT_NODE: 11,
                    DOCUMENT_NODE: 9,
                    DOCUMENT_POSITION_CONTAINED_BY: 16,
                    DOCUMENT_POSITION_CONTAINS: 8,
                    DOCUMENT_POSITION_DISCONNECTED: 1,
                    DOCUMENT_POSITION_FOLLOWING: 4,
                    DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
                    DOCUMENT_POSITION_PRECEDING: 2,
                    DOCUMENT_TYPE_NODE: 10,
                    draggable: false,
                    ELEMENT_NODE: 1,
                    ENTITY_NODE: 6,
                    ENTITY_REFERENCE_NODE: 5,
      firstChild: [object Text] {... },
                    firstElementChild: null,
      focus: function focus() {[native code]},
      getAttribute: function getAttribute() {[native code]},
      getAttributeNames: function getAttributeNames() {[native code]},
      getAttributeNode: function getAttributeNode() {[native code]},
      getAttributeNodeNS: function getAttributeNodeNS() {[native code]},
      getAttributeNS: function getAttributeNS() {[native code]},
      getBoundingClientRect: function getBoundingClientRect() {[native code]},
      getClientRects: function getClientRects() {[native code]},
      getDestinationInsertionPoints: function getDestinationInsertionPoints() {[native code]},
      getElementsByClassName: function getElementsByClassName() {[native code]},
      getElementsByTagName: function getElementsByTagName() {[native code]},
      getElementsByTagNameNS: function getElementsByTagNameNS() {[native code]},
      getRootNode: function getRootNode() {[native code]},
      hasAttribute: function hasAttribute() {[native code]},
      hasAttributeNS: function hasAttributeNS() {[native code]},
      hasAttributes: function hasAttributes() {[native code]},
      hasChildNodes: function hasChildNodes() {[native code]},
      hasPointerCapture: function hasPointerCapture() {[native code]},
                    hidden: false,
                    id: "",
                    innerHTML: "Press enter",
                    innerText: "Press enter",
                    inputMode: "",
      insertAdjacentElement: function insertAdjacentElement() {[native code]},
      insertAdjacentHTML: function insertAdjacentHTML() {[native code]},
      insertAdjacentText: function insertAdjacentText() {[native code]},
      insertBefore: function insertBefore() {[native code]},
                    isConnected: true,
                    isContentEditable: true,
      isDefaultNamespace: function isDefaultNamespace() {[native code]},
      isEqualNode: function isEqualNode() {[native code]},
      isSameNode: function isSameNode() {[native code]},
                    lang: "",
                    lastChild: [circular object Text],
                    lastElementChild: null,
                    localName: "li",
      lookupNamespaceURI: function lookupNamespaceURI() {[native code]},
      lookupPrefix: function lookupPrefix() {[native code]},
      matches: function matches() {[native code]},
                    namespaceURI: "http://www.w3.org/1999/xhtml",
                    nextElementSibling: [circular object HTMLLIElement] :
  <li><br></li>,
                        nextSibling: [circular object HTMLLIElement] :
  <li><br></li>,
                            nodeName: "LI",
                            nodeType: 1,
                            nodeValue: null,
                            nonce: "",
      normalize: function normalize() {[native code]},
                            NOTATION_NODE: 12,
                            offsetHeight: 18,
                            offsetLeft: 48,
      offsetParent: [object HTMLBodyElement] {... },
                            offsetTop: 16,
                            offsetWidth: 385,
                            onabort: null,
                            onauxclick: null,
                            onbeforecopy: null,
                            onbeforecut: null,
                            onbeforepaste: null,
                            onblur: null,
                            oncancel: null,
                            oncanplay: null,
                            oncanplaythrough: null,
                            onchange: null,
                            onclick: null,
                            onclose: null,
                            oncontextmenu: null,
                            oncopy: null,
                            oncuechange: null,
                            oncut: null,
                            ondblclick: null,
                            ondrag: null,
                            ondragend: null,
                            ondragenter: null,
                            ondragleave: null,
                            ondragover: null,
                            ondragstart: null,
                            ondrop: null,
                            ondurationchange: null,
                            onemptied: null,
                            onended: null,
                            onerror: null,
                            onfocus: null,
                            onfullscreenchange: null,
                            onfullscreenerror: null,
                            ongotpointercapture: null,
                            oninput: null,
                            oninvalid: null,
                            onkeydown: null,
                            onkeypress: null,
                            onkeyup: null,
                            onload: null,
                            onloadeddata: null,
                            onloadedmetadata: null,
                            onloadstart: null,
                            onlostpointercapture: null,
                            onmousedown: null,
                            onmouseenter: null,
                            onmouseleave: null,
                            onmousemove: null,
                            onmouseout: null,
                            onmouseover: null,
                            onmouseup: null,
                            onmousewheel: null,
                            onpaste: null,
                            onpause: null,
                            onplay: null,
                            onplaying: null,
                            onpointercancel: null,
                            onpointerdown: null,
                            onpointerenter: null,
                            onpointerleave: null,
                            onpointermove: null,
                            onpointerout: null,
                            onpointerover: null,
                            onpointerup: null,
                            onprogress: null,
                            onratechange: null,
                            onreset: null,
                            onresize: null,
                            onscroll: null,
                            onsearch: null,
                            onseeked: null,
                            onseeking: null,
                            onselect: null,
                            onselectionchange: null,
                            onselectstart: null,
                            onstalled: null,
                            onsubmit: null,
                            onsuspend: null,
                            ontimeupdate: null,
                            ontoggle: null,
                            onvolumechange: null,
                            onwaiting: null,
                            onwebkitfullscreenchange: null,
                            onwebkitfullscreenerror: null,
                            onwheel: null,
      outerHTML: "<li>Press enter</li>",
                            outerText: "Press enter",
                            ownerDocument: [circular object HTMLDocument],
                            parentElement: [circular object HTMLOListElement] :
  <ol contenteditable="" oninput="">
                                <li>Press enter</li><li><br></li>
      </ol>,
                                parentNode: [circular object HTMLOListElement] :
  <ol contenteditable="" oninput="">
                                    <li>Press enter</li><li><br></li>
      </ol>,
                                    prefix: null,
      prepend: function prepend() {[native code]},
                                    previousElementSibling: null,
      previousSibling: [object Text] {... },
                                    PROCESSING_INSTRUCTION_NODE: 7,
      querySelector: function querySelector() {[native code]},
      querySelectorAll: function querySelectorAll() {[native code]},
      releasePointerCapture: function releasePointerCapture() {[native code]},
      remove: function remove() {[native code]},
      removeAttribute: function removeAttribute() {[native code]},
      removeAttributeNode: function removeAttributeNode() {[native code]},
      removeAttributeNS: function removeAttributeNS() {[native code]},
      removeChild: function removeChild() {[native code]},
      removeEventListener: function removeEventListener() {[native code]},
      replaceChild: function replaceChild() {[native code]},
      replaceWith: function replaceWith() {[native code]},
      requestFullscreen: function requestFullscreen() {[native code]},
      requestPointerLock: function requestPointerLock() {[native code]},
      scroll: function scroll() {[native code]},
      scrollBy: function scrollBy() {[native code]},
                                    scrollHeight: 18,
      scrollIntoView: function scrollIntoView() {[native code]},
      scrollIntoViewIfNeeded: function scrollIntoViewIfNeeded() {[native code]},
                                    scrollLeft: 0,
      scrollTo: function scrollTo() {[native code]},
                                    scrollTop: 0,
                                    scrollWidth: 385,
      setAttribute: function setAttribute() {[native code]},
      setAttributeNode: function setAttributeNode() {[native code]},
      setAttributeNodeNS: function setAttributeNodeNS() {[native code]},
      setAttributeNS: function setAttributeNS() {[native code]},
      setPointerCapture: function setPointerCapture() {[native code]},
                                    shadowRoot: null,
                                    slot: "",
                                    spellcheck: true,
      style: [object CSSStyleDeclaration] {... },
                                    tabIndex: -1,
                                    tagName: "LI",
                                    TEXT_NODE: 3,
                                    textContent: "Press enter",
                                    title: "",
      toggleAttribute: function toggleAttribute() {[native code]},
                                    translate: true,
                                    type: "",
                                    value: 0,
      webkitMatchesSelector: function webkitMatchesSelector() {[native code]},
      webkitRequestFullScreen: function webkitRequestFullScreen() {[native code]},
      webkitRequestFullscreen: function webkitRequestFullscreen() {[native code]}
                                    },
    removedNodes: [object NodeList] {
                                        entries: function entries() {[native code]},
      forEach: function forEach() {[native code]},
      item: function item() {[native code]},
      keys: function keys() {[native code]},
                                    length: 0,
      values: function values() {[native code]}
                                    },
                                    target: [circular object HTMLOListElement] :
  <ol contenteditable="" oninput="">
                                        <li>Press enter</li><li><br></li>
    </ol>,
                                        type: "childList"
                                      }
  [object MutationRecord] {
                                            addedNodes: [object NodeList] {
                                            0: [object HTMLBRElement] {... },
      entries: function entries() {[native code]},
      forEach: function forEach() {[native code]},
      item: function item() {[native code]},
      keys: function keys() {[native code]},
                                        length: 1,
      values: function values() {[native code]}
                                        },
                                        attributeName: null,
                                        attributeNamespace: null,
                                        nextSibling: null,
                                        oldValue: null,
                                        previousSibling: null,
    removedNodes: [object NodeList] {
                                            entries: function entries() {[native code]},
      forEach: function forEach() {[native code]},
      item: function item() {[native code]},
      keys: function keys() {[native code]},
                                        length: 0,
      values: function values() {[native code]}
                                        },
    target: [object HTMLLIElement] {
                                            accessKey: "",
      addEventListener: function addEventListener() {[native code]},
      after: function after() {[native code]},
      animate: function animate() {[native code]},
      append: function append() {[native code]},
      appendChild: function appendChild() {[native code]},
                                        assignedSlot: null,
      attachShadow: function attachShadow() {[native code]},
                                        ATTRIBUTE_NODE: 2,
      attributes: [object NamedNodeMap] {... },
      attributeStyleMap: [object StylePropertyMap] {... },
                                        autocapitalize: "",
                                        baseURI: "https://null.jsbin.com/runner",
      before: function before() {[native code]},
      blur: function blur() {[native code]},
                                        CDATA_SECTION_NODE: 4,
                                        childElementCount: 1,
      childNodes: [object NodeList] {... },
      children: [object HTMLCollection] {... },
      classList: [object DOMTokenList] {... },
                                        className: "",
      click: function click() {[native code]},
                                        clientHeight: 18,
                                        clientLeft: 0,
                                        clientTop: 0,
                                        clientWidth: 385,
      cloneNode: function cloneNode() {[native code]},
      closest: function closest() {[native code]},
                                        COMMENT_NODE: 8,
      compareDocumentPosition: function compareDocumentPosition() {[native code]},
      computedStyleMap: function computedStyleMap() {[native code]},
      contains: function contains() {[native code]},
                                        contentEditable: "inherit",
      createShadowRoot: function createShadowRoot() {[native code]},
      dataset: [object DOMStringMap] {... },
                                        dir: "",
      dispatchEvent: function dispatchEvent() {[native code]},
                                        DOCUMENT_FRAGMENT_NODE: 11,
                                        DOCUMENT_NODE: 9,
                                        DOCUMENT_POSITION_CONTAINED_BY: 16,
                                        DOCUMENT_POSITION_CONTAINS: 8,
                                        DOCUMENT_POSITION_DISCONNECTED: 1,
                                        DOCUMENT_POSITION_FOLLOWING: 4,
                                        DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
                                        DOCUMENT_POSITION_PRECEDING: 2,
                                        DOCUMENT_TYPE_NODE: 10,
                                        draggable: false,
                                        ELEMENT_NODE: 1,
                                        ENTITY_NODE: 6,
                                        ENTITY_REFERENCE_NODE: 5,
                                        firstChild: [circular object HTMLBRElement] :
  <br>,
                                            firstElementChild: [circular object HTMLBRElement] :
  <br>,
      focus: function focus() {[native code]},
      getAttribute: function getAttribute() {[native code]},
      getAttributeNames: function getAttributeNames() {[native code]},
      getAttributeNode: function getAttributeNode() {[native code]},
      getAttributeNodeNS: function getAttributeNodeNS() {[native code]},
      getAttributeNS: function getAttributeNS() {[native code]},
      getBoundingClientRect: function getBoundingClientRect() {[native code]},
      getClientRects: function getClientRects() {[native code]},
      getDestinationInsertionPoints: function getDestinationInsertionPoints() {[native code]},
      getElementsByClassName: function getElementsByClassName() {[native code]},
      getElementsByTagName: function getElementsByTagName() {[native code]},
      getElementsByTagNameNS: function getElementsByTagNameNS() {[native code]},
      getRootNode: function getRootNode() {[native code]},
      hasAttribute: function hasAttribute() {[native code]},
      hasAttributeNS: function hasAttributeNS() {[native code]},
      hasAttributes: function hasAttributes() {[native code]},
      hasChildNodes: function hasChildNodes() {[native code]},
      hasPointerCapture: function hasPointerCapture() {[native code]},
                                                hidden: false,
                                                id: "",
      innerHTML: "<br>",
                                                innerText: "
                                            ",
                                                inputMode: "",
      insertAdjacentElement: function insertAdjacentElement() {[native code]},
      insertAdjacentHTML: function insertAdjacentHTML() {[native code]},
      insertAdjacentText: function insertAdjacentText() {[native code]},
      insertBefore: function insertBefore() {[native code]},
                                                    isConnected: true,
                                                    isContentEditable: true,
      isDefaultNamespace: function isDefaultNamespace() {[native code]},
      isEqualNode: function isEqualNode() {[native code]},
      isSameNode: function isSameNode() {[native code]},
                                                    lang: "",
                                                    lastChild: [circular object HTMLBRElement] :
  <br>,
                                                        lastElementChild: [circular object HTMLBRElement] :
  <br>,
                                                            localName: "li",
      lookupNamespaceURI: function lookupNamespaceURI() {[native code]},
      lookupPrefix: function lookupPrefix() {[native code]},
      matches: function matches() {[native code]},
                                                            namespaceURI: "http://www.w3.org/1999/xhtml",
                                                            nextElementSibling: null,
      nextSibling: [object Text] {... },
                                                            nodeName: "LI",
                                                            nodeType: 1,
                                                            nodeValue: null,
                                                            nonce: "",
      normalize: function normalize() {[native code]},
                                                            NOTATION_NODE: 12,
                                                            offsetHeight: 18,
                                                            offsetLeft: 48,
      offsetParent: [object HTMLBodyElement] {... },
                                                            offsetTop: 34,
                                                            offsetWidth: 385,
                                                            onabort: null,
                                                            onauxclick: null,
                                                            onbeforecopy: null,
                                                            onbeforecut: null,
                                                            onbeforepaste: null,
                                                            onblur: null,
                                                            oncancel: null,
                                                            oncanplay: null,
                                                            oncanplaythrough: null,
                                                            onchange: null,
                                                            onclick: null,
                                                            onclose: null,
                                                            oncontextmenu: null,
                                                            oncopy: null,
                                                            oncuechange: null,
                                                            oncut: null,
                                                            ondblclick: null,
                                                            ondrag: null,
                                                            ondragend: null,
                                                            ondragenter: null,
                                                            ondragleave: null,
                                                            ondragover: null,
                                                            ondragstart: null,
                                                            ondrop: null,
                                                            ondurationchange: null,
                                                            onemptied: null,
                                                            onended: null,
                                                            onerror: null,
                                                            onfocus: null,
                                                            onfullscreenchange: null,
                                                            onfullscreenerror: null,
                                                            ongotpointercapture: null,
                                                            oninput: null,
                                                            oninvalid: null,
                                                            onkeydown: null,
                                                            onkeypress: null,
                                                            onkeyup: null,
                                                            onload: null,
                                                            onloadeddata: null,
                                                            onloadedmetadata: null,
                                                            onloadstart: null,
                                                            onlostpointercapture: null,
                                                            onmousedown: null,
                                                            onmouseenter: null,
                                                            onmouseleave: null,
                                                            onmousemove: null,
                                                            onmouseout: null,
                                                            onmouseover: null,
                                                            onmouseup: null,
                                                            onmousewheel: null,
                                                            onpaste: null,
                                                            onpause: null,
                                                            onplay: null,
                                                            onplaying: null,
                                                            onpointercancel: null,
                                                            onpointerdown: null,
                                                            onpointerenter: null,
                                                            onpointerleave: null,
                                                            onpointermove: null,
                                                            onpointerout: null,
                                                            onpointerover: null,
                                                            onpointerup: null,
                                                            onprogress: null,
                                                            onratechange: null,
                                                            onreset: null,
                                                            onresize: null,
                                                            onscroll: null,
                                                            onsearch: null,
                                                            onseeked: null,
                                                            onseeking: null,
                                                            onselect: null,
                                                            onselectionchange: null,
                                                            onselectstart: null,
                                                            onstalled: null,
                                                            onsubmit: null,
                                                            onsuspend: null,
                                                            ontimeupdate: null,
                                                            ontoggle: null,
                                                            onvolumechange: null,
                                                            onwaiting: null,
                                                            onwebkitfullscreenchange: null,
                                                            onwebkitfullscreenerror: null,
                                                            onwheel: null,
      outerHTML: "<li><br></li>",
                                                            outerText: "
                                                        ",
      ownerDocument: [object HTMLDocument] {... },
      parentElement: [object HTMLOListElement] {... },
                                                                parentNode: [circular object HTMLOListElement] :
  <ol contenteditable="" oninput="">
                                                                    <li>Press enter</li><li><br></li>
      </ol>,
                                                                    prefix: null,
      prepend: function prepend() {[native code]},
      previousElementSibling: [object HTMLLIElement] {... },
                                                                    previousSibling: [circular object HTMLLIElement] :
  <li>Press enter</li>,
                                                                        PROCESSING_INSTRUCTION_NODE: 7,
      querySelector: function querySelector() {[native code]},
      querySelectorAll: function querySelectorAll() {[native code]},
      releasePointerCapture: function releasePointerCapture() {[native code]},
      remove: function remove() {[native code]},
      removeAttribute: function removeAttribute() {[native code]},
      removeAttributeNode: function removeAttributeNode() {[native code]},
      removeAttributeNS: function removeAttributeNS() {[native code]},
      removeChild: function removeChild() {[native code]},
      removeEventListener: function removeEventListener() {[native code]},
      replaceChild: function replaceChild() {[native code]},
      replaceWith: function replaceWith() {[native code]},
      requestFullscreen: function requestFullscreen() {[native code]},
      requestPointerLock: function requestPointerLock() {[native code]},
      scroll: function scroll() {[native code]},
      scrollBy: function scrollBy() {[native code]},
                                                                    scrollHeight: 18,
      scrollIntoView: function scrollIntoView() {[native code]},
      scrollIntoViewIfNeeded: function scrollIntoViewIfNeeded() {[native code]},
                                                                    scrollLeft: 0,
      scrollTo: function scrollTo() {[native code]},
                                                                    scrollTop: 0,
                                                                    scrollWidth: 385,
      setAttribute: function setAttribute() {[native code]},
      setAttributeNode: function setAttributeNode() {[native code]},
      setAttributeNodeNS: function setAttributeNodeNS() {[native code]},
      setAttributeNS: function setAttributeNS() {[native code]},
      setPointerCapture: function setPointerCapture() {[native code]},
                                                                    shadowRoot: null,
                                                                    slot: "",
                                                                    spellcheck: true,
      style: [object CSSStyleDeclaration] {... },
                                                                    tabIndex: -1,
                                                                    tagName: "LI",
                                                                    TEXT_NODE: 3,
                                                                    textContent: "",
                                                                    title: "",
      toggleAttribute: function toggleAttribute() {[native code]},
                                                                    translate: true,
                                                                    type: "",
                                                                    value: 0,
      webkitMatchesSelector: function webkitMatchesSelector() {[native code]},
      webkitRequestFullScreen: function webkitRequestFullScreen() {[native code]},
      webkitRequestFullscreen: function webkitRequestFullscreen() {[native code]}
                                                                    },
                                                                    type: "childList"
                                                                  }
  [object MutationRecord] {
                                                                        addedNodes: [object NodeList] {
                                                                        0: [object Text] {... },
      entries: function entries() {[native code]},
      forEach: function forEach() {[native code]},
      item: function item() {[native code]},
      keys: function keys() {[native code]},
                                                                    length: 1,
      values: function values() {[native code]}
                                                                    },
                                                                    attributeName: null,
                                                                    attributeNamespace: null,
    nextSibling: [object HTMLBRElement] {
                                                                        accessKey: "",
      addEventListener: function addEventListener() {[native code]},
      after: function after() {[native code]},
      animate: function animate() {[native code]},
      append: function append() {[native code]},
      appendChild: function appendChild() {[native code]},
                                                                    assignedSlot: null,
      attachShadow: function attachShadow() {[native code]},
                                                                    ATTRIBUTE_NODE: 2,
      attributes: [object NamedNodeMap] {... },
      attributeStyleMap: [object StylePropertyMap] {... },
                                                                    autocapitalize: "",
                                                                    baseURI: "https://null.jsbin.com/runner",
      before: function before() {[native code]},
      blur: function blur() {[native code]},
                                                                    CDATA_SECTION_NODE: 4,
                                                                    childElementCount: 0,
      childNodes: [object NodeList] {... },
      children: [object HTMLCollection] {... },
      classList: [object DOMTokenList] {... },
                                                                    className: "",
                                                                    clear: "",
      click: function click() {[native code]},
                                                                    clientHeight: 0,
                                                                    clientLeft: 0,
                                                                    clientTop: 0,
                                                                    clientWidth: 0,
      cloneNode: function cloneNode() {[native code]},
      closest: function closest() {[native code]},
                                                                    COMMENT_NODE: 8,
      compareDocumentPosition: function compareDocumentPosition() {[native code]},
      computedStyleMap: function computedStyleMap() {[native code]},
      contains: function contains() {[native code]},
                                                                    contentEditable: "inherit",
      createShadowRoot: function createShadowRoot() {[native code]},
      dataset: [object DOMStringMap] {... },
                                                                    dir: "",
      dispatchEvent: function dispatchEvent() {[native code]},
                                                                    DOCUMENT_FRAGMENT_NODE: 11,
                                                                    DOCUMENT_NODE: 9,
                                                                    DOCUMENT_POSITION_CONTAINED_BY: 16,
                                                                    DOCUMENT_POSITION_CONTAINS: 8,
                                                                    DOCUMENT_POSITION_DISCONNECTED: 1,
                                                                    DOCUMENT_POSITION_FOLLOWING: 4,
                                                                    DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
                                                                    DOCUMENT_POSITION_PRECEDING: 2,
                                                                    DOCUMENT_TYPE_NODE: 10,
                                                                    draggable: false,
                                                                    ELEMENT_NODE: 1,
                                                                    ENTITY_NODE: 6,
                                                                    ENTITY_REFERENCE_NODE: 5,
                                                                    firstChild: null,
                                                                    firstElementChild: null,
      focus: function focus() {[native code]},
      getAttribute: function getAttribute() {[native code]},
      getAttributeNames: function getAttributeNames() {[native code]},
      getAttributeNode: function getAttributeNode() {[native code]},
      getAttributeNodeNS: function getAttributeNodeNS() {[native code]},
      getAttributeNS: function getAttributeNS() {[native code]},
      getBoundingClientRect: function getBoundingClientRect() {[native code]},
      getClientRects: function getClientRects() {[native code]},
      getDestinationInsertionPoints: function getDestinationInsertionPoints() {[native code]},
      getElementsByClassName: function getElementsByClassName() {[native code]},
      getElementsByTagName: function getElementsByTagName() {[native code]},
      getElementsByTagNameNS: function getElementsByTagNameNS() {[native code]},
      getRootNode: function getRootNode() {[native code]},
      hasAttribute: function hasAttribute() {[native code]},
      hasAttributeNS: function hasAttributeNS() {[native code]},
      hasAttributes: function hasAttributes() {[native code]},
      hasChildNodes: function hasChildNodes() {[native code]},
      hasPointerCapture: function hasPointerCapture() {[native code]},
                                                                    hidden: false,
                                                                    id: "",
                                                                    innerHTML: "",
                                                                    innerText: "",
                                                                    inputMode: "",
      insertAdjacentElement: function insertAdjacentElement() {[native code]},
      insertAdjacentHTML: function insertAdjacentHTML() {[native code]},
      insertAdjacentText: function insertAdjacentText() {[native code]},
      insertBefore: function insertBefore() {[native code]},
                                                                    isConnected: true,
                                                                    isContentEditable: true,
      isDefaultNamespace: function isDefaultNamespace() {[native code]},
      isEqualNode: function isEqualNode() {[native code]},
      isSameNode: function isSameNode() {[native code]},
                                                                    lang: "",
                                                                    lastChild: null,
                                                                    lastElementChild: null,
                                                                    localName: "br",
      lookupNamespaceURI: function lookupNamespaceURI() {[native code]},
      lookupPrefix: function lookupPrefix() {[native code]},
      matches: function matches() {[native code]},
                                                                    namespaceURI: "http://www.w3.org/1999/xhtml",
                                                                    nextElementSibling: null,
                                                                    nextSibling: null,
                                                                    nodeName: "BR",
                                                                    nodeType: 1,
                                                                    nodeValue: null,
                                                                    nonce: "",
      normalize: function normalize() {[native code]},
                                                                    NOTATION_NODE: 12,
                                                                    offsetHeight: 0,
                                                                    offsetLeft: 0,
      offsetParent: [object HTMLBodyElement] {... },
                                                                    offsetTop: 0,
                                                                    offsetWidth: 0,
                                                                    onabort: null,
                                                                    onauxclick: null,
                                                                    onbeforecopy: null,
                                                                    onbeforecut: null,
                                                                    onbeforepaste: null,
                                                                    onblur: null,
                                                                    oncancel: null,
                                                                    oncanplay: null,
                                                                    oncanplaythrough: null,
                                                                    onchange: null,
                                                                    onclick: null,
                                                                    onclose: null,
                                                                    oncontextmenu: null,
                                                                    oncopy: null,
                                                                    oncuechange: null,
                                                                    oncut: null,
                                                                    ondblclick: null,
                                                                    ondrag: null,
                                                                    ondragend: null,
                                                                    ondragenter: null,
                                                                    ondragleave: null,
                                                                    ondragover: null,
                                                                    ondragstart: null,
                                                                    ondrop: null,
                                                                    ondurationchange: null,
                                                                    onemptied: null,
                                                                    onended: null,
                                                                    onerror: null,
                                                                    onfocus: null,
                                                                    onfullscreenchange: null,
                                                                    onfullscreenerror: null,
                                                                    ongotpointercapture: null,
                                                                    oninput: null,
                                                                    oninvalid: null,
                                                                    onkeydown: null,
                                                                    onkeypress: null,
                                                                    onkeyup: null,
                                                                    onload: null,
                                                                    onloadeddata: null,
                                                                    onloadedmetadata: null,
                                                                    onloadstart: null,
                                                                    onlostpointercapture: null,
                                                                    onmousedown: null,
                                                                    onmouseenter: null,
                                                                    onmouseleave: null,
                                                                    onmousemove: null,
                                                                    onmouseout: null,
                                                                    onmouseover: null,
                                                                    onmouseup: null,
                                                                    onmousewheel: null,
                                                                    onpaste: null,
                                                                    onpause: null,
                                                                    onplay: null,
                                                                    onplaying: null,
                                                                    onpointercancel: null,
                                                                    onpointerdown: null,
                                                                    onpointerenter: null,
                                                                    onpointerleave: null,
                                                                    onpointermove: null,
                                                                    onpointerout: null,
                                                                    onpointerover: null,
                                                                    onpointerup: null,
                                                                    onprogress: null,
                                                                    onratechange: null,
                                                                    onreset: null,
                                                                    onresize: null,
                                                                    onscroll: null,
                                                                    onsearch: null,
                                                                    onseeked: null,
                                                                    onseeking: null,
                                                                    onselect: null,
                                                                    onselectionchange: null,
                                                                    onselectstart: null,
                                                                    onstalled: null,
                                                                    onsubmit: null,
                                                                    onsuspend: null,
                                                                    ontimeupdate: null,
                                                                    ontoggle: null,
                                                                    onvolumechange: null,
                                                                    onwaiting: null,
                                                                    onwebkitfullscreenchange: null,
                                                                    onwebkitfullscreenerror: null,
                                                                    onwheel: null,
      outerHTML: "<br>",
                                                                    outerText: "",
      ownerDocument: [object HTMLDocument] {... },
      parentElement: [object HTMLLIElement] {... },
                                                                        parentNode: [circular object HTMLLIElement] :
  <li>ELEMENT_NODE<br></li>,
                                                                            prefix: null,
      prepend: function prepend() {[native code]},
                                                                            previousElementSibling: null,
                                                                            previousSibling: [circular object Text],
                                                                            PROCESSING_INSTRUCTION_NODE: 7,
      querySelector: function querySelector() {[native code]},
      querySelectorAll: function querySelectorAll() {[native code]},
      releasePointerCapture: function releasePointerCapture() {[native code]},
      remove: function remove() {[native code]},
      removeAttribute: function removeAttribute() {[native code]},
      removeAttributeNode: function removeAttributeNode() {[native code]},
      removeAttributeNS: function removeAttributeNS() {[native code]},
      removeChild: function removeChild() {[native code]},
      removeEventListener: function removeEventListener() {[native code]},
      replaceChild: function replaceChild() {[native code]},
      replaceWith: function replaceWith() {[native code]},
      requestFullscreen: function requestFullscreen() {[native code]},
      requestPointerLock: function requestPointerLock() {[native code]},
      scroll: function scroll() {[native code]},
      scrollBy: function scrollBy() {[native code]},
                                                                            scrollHeight: 0,
      scrollIntoView: function scrollIntoView() {[native code]},
      scrollIntoViewIfNeeded: function scrollIntoViewIfNeeded() {[native code]},
                                                                            scrollLeft: 0,
      scrollTo: function scrollTo() {[native code]},
                                                                            scrollTop: 0,
                                                                            scrollWidth: 0,
      setAttribute: function setAttribute() {[native code]},
      setAttributeNode: function setAttributeNode() {[native code]},
      setAttributeNodeNS: function setAttributeNodeNS() {[native code]},
      setAttributeNS: function setAttributeNS() {[native code]},
      setPointerCapture: function setPointerCapture() {[native code]},
                                                                            shadowRoot: null,
                                                                            slot: "",
                                                                            spellcheck: true,
      style: [object CSSStyleDeclaration] {... },
                                                                            tabIndex: -1,
                                                                            tagName: "BR",
                                                                            TEXT_NODE: 3,
                                                                            textContent: "",
                                                                            title: "",
      toggleAttribute: function toggleAttribute() {[native code]},
                                                                            translate: true,
      webkitMatchesSelector: function webkitMatchesSelector() {[native code]},
      webkitRequestFullScreen: function webkitRequestFullScreen() {[native code]},
      webkitRequestFullscreen: function webkitRequestFullscreen() {[native code]}
                                                                            },
                                                                            oldValue: null,
                                                                            previousSibling: null,
    removedNodes: [object NodeList] {
                                                                                entries: function entries() {[native code]},
      forEach: function forEach() {[native code]},
      item: function item() {[native code]},
      keys: function keys() {[native code]},
                                                                            length: 0,
      values: function values() {[native code]}
                                                                            },
                                                                            target: [circular object HTMLLIElement] :
  <li>ELEMENT_NODE<br></li>,
                                                                              type: "childList"
  }